# Generated by Django 3.1.2 on 2020-10-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'No Mail'), (1, 'To Admin'), (2, 'To User')], default=0),
        ),
    ]
