# Generated by Django 3.1.2 on 2020-10-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_time',
            field=models.DateTimeField(null=True),
        ),
    ]
